This notebook (and the slides from lecture 8) will help you go straight from training a model in Colab to deploying it in a webpage with TensorFlow.js - without having to leave the browser.

Configure this notebook to work with your GitHub account by populating these fields.

In [1]:
!pip install tensorflowjs

You are using pip version 18.0, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [2]:
# your github username
USER_NAME = "zy2293" 

# the email associated with your commits
# (may not matter if you leave it as this)
USER_EMAIL = "zy2293@columbia.edu" 

# the user token you've created (see the lecture 8 slides for instructions)
TOKEN = "34b82bdf21fa201df7e6f2e9706b40938ffabafd" 

# site name
# for example, if my user_name is "foo", then this notebook will create
# a site at https://foo.github.io/hw4/
SITE_NAME = "hw4"

Next, run this cell to configure git.

In [3]:
!git config --global user.email {USER_NAME}
!git config --global user.name  {USER_EMAIL}

Clone your GitHub pages repo (see the lecture 8 slides for instructions on how to create one).

In [4]:
import os
repo_path = USER_NAME + '.github.io'
if not os.path.exists(os.path.join(os.getcwd(), repo_path)):
  !git clone https://{USER_NAME}:{TOKEN}@github.com/{USER_NAME}/{USER_NAME}.github.io

In [5]:
os.chdir(repo_path)
!git pull

Already up-to-date.


Create a folder for your site.

In [6]:
project_path = os.path.join(os.getcwd(), SITE_NAME)
if not os.path.exists(project_path): 
  os.mkdir(project_path)
os.chdir(project_path)

These paths will be used by the converter script.

In [7]:
# DO NOT MODIFY
MODEL_DIR = os.path.join(project_path, "model_js")
if not os.path.exists(MODEL_DIR):
  os.mkdir(MODEL_DIR)

As an example, we will create and vectorize a few documents. (Check out https://www.gutenberg.org/ for a bunch of free e-books.)

In [8]:
# read in first 1000 sentences from Alice in Wonderland
import urllib.request
import nltk

def read_books(url, starting_sent):
    response = urllib.request.urlopen(url)
    data = response.readlines()
    
    book = []
    read = False # won't start reading until meeting the first sentence in the content
    count = 0
    for line in data:
        line = line.decode('utf-8')
        if line.startswith('\r\n'):
            pass
        else:
            if line.startswith(starting_sent):
                read = True
            if read:
                count += 1
                book.append(line[:-2])
    
    book = " ".join(book)   
#    sentences = re.split(r' *[\.\?!][\'"\)\]]* *', book) # split texts into sentences
    sentences = nltk.sent_tokenize(book)
    if len(sentences) >= 1000:
        return sentences[:1000]
    else:
        return sentences

In [9]:
# Dracula
dracula_url = "http://www.gutenberg.org/cache/epub/345/pg345.txt"
start_line = "_3 May. Bistritz._--Left Munich at 8:35 P. M., on 1st May"
dracula = read_books(dracula_url, start_line)

In [10]:
# Tower of London
tower_url = "https://www.gutenberg.org/files/58271/58271-0.txt"
start_line = "The Tower of London is the most interesting fortress in Great"
tower_of_london = read_books(tower_url, start_line)

In [11]:
# Blue Jacket
jacket_url = "http://www.gutenberg.org/cache/epub/58270/pg58270.txt"
start_line = "The big bell of Woolwich Dockyard had just commenced its"
blue_jacket = read_books(jacket_url, start_line)

In [12]:
all_books = dracula
all_books.extend(tower_of_london)
all_books.extend(blue_jacket)

In [13]:
import numpy as np
x_train = all_books
y_train = np.zeros(len(x_train))
# 0: Dracula; 1: Tower of London; 2: Blue Jacket
y_train[1000:2000] = 1
y_train[2000:] = 2

Tokenize the documents, create a word index (word -> number).

In [14]:
max_len = 100
num_words = 10000
from keras.preprocessing.text import Tokenizer
# Fit the tokenizer on the training data
t = Tokenizer(num_words=num_words)
t.fit_on_texts(x_train)

Using TensorFlow backend.


In [15]:
len(t.word_index)

8425

Here's how we vectorize a document.

In [16]:
vectorized = t.texts_to_sequences(dracula)
# print(vectorized)

Apply padding if necessary.

In [17]:
from keras.preprocessing.sequence import pad_sequences
padded = pad_sequences(vectorized, maxlen=max_len, padding='post')

In [18]:
print(padded)

[[1037   95    0 ...    0    0    0]
 [ 815  201 4086 ...    0    0    0]
 [2739 2740  582 ...    0    0    0]
 ...
 [   8  193  480 ...    0    0    0]
 [  71  989 8424 ...    0    0    0]
 [   8  285  158 ...    0    0    0]]


We will save the word index in metadata. Later, we'll use it to convert words typed in the browser to numbers for prediction.

In [19]:
metadata = {
  'word_index': t.word_index,
  'max_len': max_len,
  'vocabulary_size': num_words,
}

Define a model.

In [75]:
embedding_size = 20
n_classes = 3
epochs = 20

import keras
model = keras.Sequential()
model.add(keras.layers.Embedding(num_words, embedding_size, input_shape=(max_len,)))
#model.add(keras.layers.Flatten())
model.add(keras.layers.LSTM(64, return_sequences=True))
model.add(keras.layers.LSTM(16, return_sequences=False))
model.add(keras.layers.Dense(3, activation='softmax'))
model.compile('rmsprop', 'sparse_categorical_crossentropy', metrics=['accuracy'])
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_8 (Embedding)      (None, 100, 20)           200000    
_________________________________________________________________
lstm_15 (LSTM)               (None, 100, 64)           21760     
_________________________________________________________________
lstm_16 (LSTM)               (None, 16)                5184      
_________________________________________________________________
dense_9 (Dense)              (None, 3)                 51        
Total params: 226,995
Trainable params: 226,995
Non-trainable params: 0
_________________________________________________________________


Prepare some training data.

In [21]:
x_train = t.texts_to_sequences(x_train)
x_train = pad_sequences(x_train, maxlen=max_len, padding='post')
print(x_train)

[[1037   95    0 ...    0    0    0]
 [ 815  201 4086 ...    0    0    0]
 [2739 2740  582 ...    0    0    0]
 ...
 [   8  193  480 ...    0    0    0]
 [  71  989 8424 ...    0    0    0]
 [   8  285  158 ...    0    0    0]]


In [76]:
model.fit(x_train, y_train, epochs=epochs)

Epoch 1/20
3000/3000 [==============================] - 14s 5ms/step - loss: 1.0997 - acc: 0.3263
Epoch 2/20
3000/3000 [==============================] - 12s 4ms/step - loss: 1.0993 - acc: 0.3140
Epoch 3/20
3000/3000 [==============================] - 12s 4ms/step - loss: 1.0992 - acc: 0.3297
Epoch 4/20
3000/3000 [==============================] - 12s 4ms/step - loss: 1.0990 - acc: 0.3360
Epoch 5/20
3000/3000 [==============================] - 12s 4ms/step - loss: 1.1037 - acc: 0.3407
Epoch 6/20
3000/3000 [==============================] - 14s 5ms/step - loss: 1.0992 - acc: 0.3537
Epoch 7/20
3000/3000 [==============================] - 12s 4ms/step - loss: 1.0993 - acc: 0.3467
Epoch 8/20
3000/3000 [==============================] - 12s 4ms/step - loss: 1.0978 - acc: 0.3553
Epoch 9/20
3000/3000 [==============================] - 12s 4ms/step - loss: 1.0817 - acc: 0.4093
Epoch 10/20
3000/3000 [==============================] - 14s 5ms/step - loss: 1.0126 - acc: 0.4800
Epoch 11/20
3000/30

Demo using the model to make predictions.

In [100]:
test_example = "_3 May. Bistritz._--Left Munich at 8:35 P. M., on 1st May"
x_test = t.texts_to_sequences([test_example])
x_test = pad_sequences(x_test, maxlen=max_len, padding='post')
print(x_test)

[[1037   95  815  201 4086   19 1635 2738  816  471   14 4087   95    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0]]


In [101]:
preds = model.predict(x_test)
print(preds)
print(np.argmax(preds))

[[0.51712114 0.01563856 0.4672403 ]]
0


Convert the model

In [102]:
import json
import tensorflowjs as tfjs

metadata_json_path = os.path.join(MODEL_DIR, 'metadata.json')
json.dump(metadata, open(metadata_json_path, 'wt'))
tfjs.converters.save_keras_model(model, MODEL_DIR)
print('\nSaved model artifcats in directory: %s' % MODEL_DIR)


Saved model artifcats in directory: /Users/zy2293/Desktop/ADL4/zy2293.github.io/hw4/model_js


Write an index.html and an index.js file configured to load our model.

In [103]:
index_html = """
<!doctype html>

<body>
  <style>
    #textfield {
      font-size: 120%;
      width: 60%;
      height: 200px;
    }
  </style>
  <h1>
    Title
  </h1>
  <hr>
  <div class="create-model">
    <button id="load-model" style="display:none">Load model</button>
  </div>
  <div>
    <div>
      <span>Vocabulary size: </span>
      <span id="vocabularySize"></span>
    </div>
    <div>
      <span>Max length: </span>
      <span id="maxLen"></span>
    </div>
  </div>
  <hr>
  <div>
    <select id="example-select" class="form-control">
      <option value="example1">Dracula</option>
      <option value="example2">The Tower of London</option>
      <option value="example3">Blue Jackets</option>
    </select>
  </div>
  <div>
    <textarea id="text-entry"></textarea>
  </div>
  <hr>
  <div>
    <span id="status">Standing by.</span>
  </div>

  <script src='https://cdn.jsdelivr.net/npm/@tensorflow/tfjs/dist/tf.min.js'></script>
  <script src='index.js'></script>
</body>
"""

In [109]:
index_js = """
const HOSTED_URLS = {
  model:
      'model_js/model.json',
  metadata:
      'model_js/metadata.json'
};

const examples = {
  'example1':
      '_3 May. Bistritz._--Left Munich at 8:35 P. M., on 1st May.',
  'example2':
      'The Port of London held a high position from the beginning of the history of Western Europe.',
  'example3':
      'Clare knew him at once, Crushe having been the second lieutenant of his last ship, and as such having twice endeavoured to get him flogged.'
};

function status(statusText) {
  console.log(statusText);
  document.getElementById('status').textContent = statusText;
}

function showMetadata(metadataJSON) {
  document.getElementById('vocabularySize').textContent =
      metadataJSON['vocabulary_size'];
  document.getElementById('maxLen').textContent =
      metadataJSON['max_len'];
}

function settextField(text, predict) {
  const textField = document.getElementById('text-entry');
  textField.value = text;
  doPredict(predict);
}

function setPredictFunction(predict) {
  const textField = document.getElementById('text-entry');
  textField.addEventListener('input', () => doPredict(predict));
}

function disableLoadModelButtons() {
  document.getElementById('load-model').style.display = 'none';
}

function doPredict(predict) {
  const textField = document.getElementById('text-entry');
  const result = predict(textField.value);
  score_string = "Class scores: ";
  for (var x in result.score) {
    score_string += x + " ->  " + result.score[x].toFixed(3) + ", "
  }
  //console.log(score_string);
  status(
      score_string + ' elapsed: ' + result.elapsed.toFixed(3) + ' ms)');
}

function prepUI(predict) {
  setPredictFunction(predict);
  const testExampleSelect = document.getElementById('example-select');
  testExampleSelect.addEventListener('change', () => {
    settextField(examples[testExampleSelect.value], predict);
  });
  settextField(examples['example1'], predict);
}

async function urlExists(url) {
  status('Testing url ' + url);
  try {
    const response = await fetch(url, {method: 'HEAD'});
    return response.ok;
  } catch (err) {
    return false;
  }
}

async function loadHostedPretrainedModel(url) {
  status('Loading pretrained model from ' + url);
  try {
    const model = await tf.loadModel(url);
    status('Done loading pretrained model.');
    disableLoadModelButtons();
    return model;
  } catch (err) {
    console.error(err);
    status('Loading pretrained model failed.');
  }
}

async function loadHostedMetadata(url) {
  status('Loading metadata from ' + url);
  try {
    const metadataJson = await fetch(url);
    const metadata = await metadataJson.json();
    status('Done loading metadata.');
    return metadata;
  } catch (err) {
    console.error(err);
    status('Loading metadata failed.');
  }
}

class Classifier {

  async init(urls) {
    this.urls = urls;
    this.model = await loadHostedPretrainedModel(urls.model);
    await this.loadMetadata();
    return this;
  }

  async loadMetadata() {
    const metadata =
        await loadHostedMetadata(this.urls.metadata);
    showMetadata(metadata);
    this.maxLen = metadata['max_len'];
    console.log('maxLen = ' + this.maxLen);
    this.wordIndex = metadata['word_index']
  }

  predict(text) {
    // Convert to lower case and remove all punctuations.
    const inputText =
        text.trim().toLowerCase().replace(/(\.|\,|\!)/g, '').split(' ');
    // Look up word indices.
    const inputBuffer = tf.buffer([1, this.maxLen], 'float32');
    for (let i = 0; i < inputText.length; ++i) {
      const word = inputText[i];
      inputBuffer.set(this.wordIndex[word], 0, i);
      //console.log(word, this.wordIndex[word], inputBuffer);
    }
    const input = inputBuffer.toTensor();
    //console.log(input);

    status('Running inference');
    const beginMs = performance.now();
    const predictOut = this.model.predict(input);
    //console.log(predictOut.dataSync());
    const score = predictOut.dataSync();//[0];
    predictOut.dispose();
    const endMs = performance.now();

    return {score: score, elapsed: (endMs - beginMs)};
  }
};

async function setup() {
  if (await urlExists(HOSTED_URLS.model)) {
    status('Model available: ' + HOSTED_URLS.model);
    const button = document.getElementById('load-model');
    button.addEventListener('click', async () => {
      const predictor = await new Classifier().init(HOSTED_URLS);
      prepUI(x => predictor.predict(x));
    });
    button.style.display = 'inline-block';
  }

  status('Standing by.');
}

setup();
"""

In [110]:
with open('index.html','w') as f:
  f.write(index_html)
  
with open('index.js','w') as f:
  f.write(index_js)

In [111]:
!ls

index.html       model_js         zy2293.github.io
index.js         python


Commit and push everything. Note: we're storing large binary files in GitHub, this isn't ideal (if you want to deploy a model down the road, better to host it in a cloud storage bucket).

In [112]:
!git add . 
!git commit -m "colab -> github"
!git push https://{USER_NAME}:{TOKEN}@github.com/{USER_NAME}/{USER_NAME}.github.io/ master

On branch master
Your branch is ahead of 'origin/master' by 6 commits.
  (use "git push" to publish your local commits)

Untracked files:
	../.DS_Store

nothing added to commit but untracked files present
Everything up-to-date


All done! Hopefully everything worked. You may need to wait a few moments for the changes to appear in your site. If not working, check the JavaScript console for errors (in Chrome: View -> Developer -> JavaScript Console).

In [113]:
print("Now, visit https://%s.github.io/%s/" % (USER_NAME, SITE_NAME))

Now, visit https://zy2293.github.io/hw4/


If you are debugging and Chrome is failing to pick up your changes, though you've verified they're present in your GitHub repo, see the second answer to: https://superuser.com/questions/89809/how-to-force-refresh-without-cache-in-google-chrome